services:
    postgres-vector:
        image: pgvector/pgvector:0.8.2-pg18-trixie
        container_name: logiceval-db-container
        environment:
            POSTGRES_DB: ${DB_NAME:-logiceval_db}
            POSTGRES_USER: ${DB_USER:-postgres}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
        ports:
            - "${DB_PORT:-5432}:5432"
        volumes:
            # - pgdata:/var/lib/postgresql/data
            - pgdata:/var/lib/postgresql/18/docker
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}",
                ]
            interval: 5s
            timeout: 5s
            retries: 5
        restart: unless-stopped

    ollama:
        image: ollama/ollama:latest
        container_name: logiceval-ollama-container
        ports:
            - "${OLLAMA_PORT:-11434}:11434"
        volumes:
            - ${OLLAMA_STORAGE_PATH:-ollama_storage}:/root/.ollama
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
        restart: unless-stopped

volumes:
    pgdata:
    ollama_storage:
